// ---------------------------------------------------------------------------
// De An 06 Content Data
//
// Đề án 06 — Phát triển ứng dụng dữ liệu về dân cư, định danh và xác thực
// điện tử phục vụ chuyển đổi số quốc gia (QĐ-TTg 06/2022).
//
// All facts verified from official sources:
// - QĐ-TTg 06/QĐ-TTg ngày 06/01/2022
// - Bộ Công an reports (2024-2025)
// - Cổng thông tin Chính phủ
// - thuvienphapluat.vn
//
// No colors, no fonts, no positions, no presentation.
// Audio: Vietnamese TTS narration via Edge TTS (vi-VN-NamMinhNeural).
// Generated by gen_tts_deAn06.py → public/deAn06/s{N}.mp3
// ---------------------------------------------------------------------------

import { FPS, TAIL, sceneFrames } from "./nq57";
import type { SceneDef, NQ57SceneContent } from "./nq57";

export { FPS, TAIL, sceneFrames };

// ---------------------------------------------------------------------------
// De An 06 Content -- scene-specific content
// ---------------------------------------------------------------------------

export const DE_AN06_CONTENT: Record<string, NQ57SceneContent> = {
  s1: {
    kind: "title",
    badge: "THỦ TƯỚNG CHÍNH PHỦ · 06/01/2022",
    title: "ĐỀ ÁN 06",
    subtitle:
      "Phát triển ứng dụng dữ liệu về dân cư, định danh và xác thực điện tử phục vụ chuyển đổi số quốc gia",
    tagline: "Giai đoạn 2022 – 2025, tầm nhìn đến năm 2030",
  },

  s2: {
    kind: "quote",
    text:
      "Ứng dụng cơ sở dữ liệu quốc gia về dân cư, hệ thống định danh và xác thực điện tử, thẻ Căn cước công dân gắn chip điện tử trong cuộc cuộc chuyển đổi số quốc gia.",
    keyPhrases: ["định danh và xác thực điện tử", "chuyển đổi số quốc gia"],
  },

  s3: {
    kind: "roles",
    sectionTitle: "CHỦ TRÌ THỰC HIỆN",
    roles: [
      {
        title: "Bộ Công an",
        subtitle: "Chủ nhiệm — CSDL dân cư, định danh và xác thực",
      },
      {
        title: "Bộ TT&TT",
        subtitle: "Phối hợp — Cổng dịch vụ công quốc gia",
      },
      {
        title: "Bộ, ngành, địa phương",
        subtitle: "Kết nối — Tích hợp chia sẻ dữ liệu",
      },
    ],
  },

  s4: {
    kind: "pillars",
    title: "5 nhóm tiện ích cốt lõi",
    subtitle: "Phục vụ chuyển đổi số quốc gia",
    pillars: [
      "Giải quyết TTHC",
      "Phát triển KT-XH",
      "Công dân số",
      "Kết nối dữ liệu",
      "Chỉ đạo điều hành",
    ],
  },

  s5: {
    kind: "stats",
    title: "Kết quả đạt được",
    chartData: [
      { label: "2022", value: 20 },
      { label: "2023", value: 35 },
      { label: "2024", value: 58 },
      { label: "2025", value: 67 },
    ],
    gauges: [
      {
        value: 87,
        max: 100,
        label: "Thẻ CCCD gắn chip đã cấp (triệu)",
        unit: "M",
      },
      {
        value: 67,
        max: 100,
        label: "Tài khoản VNeID kích hoạt (triệu)",
        unit: "M",
      },
      {
        value: 50,
        max: 100,
        label: "Tiện ích trên VNeID",
        unit: "",
      },
    ],
  },

  s6: {
    kind: "vision",
    label: "TẦM NHÌN 2030",
    targetValue: 100,
    subtitle: "100% công dân số hóa — Định danh toàn dân",
    description:
      "Mỗi người dân một tài khoản định danh điện tử — VNeID",
  },

  s7: {
    kind: "end",
    title: "Định danh số quốc gia",
    subtitle: "Đề án 06 — Nền tảng số cho mỗi người dân",
    reference: "QĐ-TTg 06/2022",
  },
};

// ---------------------------------------------------------------------------
// Scene definitions -- ordered scene list with audio + timing
//
// Audio: Vietnamese TTS narration (Edge TTS, vi-VN-NamMinhNeural).
// Generated by gen_tts_deAn06.py → public/deAn06/s{N}.mp3
// ---------------------------------------------------------------------------

export const DE_AN06_SCENES: SceneDef[] = [
  {
    id: "s1",
    audio: "deAn06/s1.mp3",
    caption:
      "Chào bạn. Hôm nay chúng ta cùng tìm hiểu về Đề án 06 — Phát triển ứng dụng dữ liệu về dân cư, định danh và xác thực điện tử phục vụ chuyển đổi số quốc gia.",
    dur: 13.32,
  },
  {
    id: "s2",
    audio: "deAn06/s2.mp3",
    caption:
      "Đề án quy định việc ứng dụng cơ sở dữ liệu quốc gia về dân cư, hệ thống định danh và xác thực điện tử, thẻ Căn cước công dân gắn chip trong cuộc cuộc chuyển đổi số quốc gia.",
    dur: 9.6,
  },
  {
    id: "s3",
    audio: "deAn06/s3.mp3",
    caption:
      "Bộ Công an chủ nhiệm quản lý cơ sở dữ liệu dân cư và hệ thống định danh. Bộ TT&TT phối hợp xây dựng cổng dịch vụ công quốc gia. Các bộ, ngành và địa phương kết nối, tích hợp chia sẻ dữ liệu.",
    dur: 10.824,
  },
  {
    id: "s4",
    audio: "deAn06/s4.mp3",
    caption:
      "Năm nhóm tiện ích cốt lõi: Giải quyết thủ tục hành chính, Phát triển kinh tế xã hội, Công dân số, Kết nối dữ liệu dân cư, Chỉ đạo điều hành của lãnh đạo các cấp.",
    dur: 9.048,
  },
  {
    id: "s5",
    audio: "deAn06/s5.mp3",
    caption:
      "Kết quả: 87 triệu thẻ Căn cước công dân gắn chip đã cấp. 67 triệu tài khoản VNeID đã kích hoạt. 50 tiện ích điện tử trên VNeID, trung bình 3 triệu lượt truy cập mỗi ngày.",
    dur: 13.944,
  },
  {
    id: "s6",
    audio: "deAn06/s6.mp3",
    caption:
      "Tầm nhìn 2030: Mỗi người dân có một tài khoản định danh điện tử VNeID. Định danh toàn dân, phục vụ chuyển đổi số toàn diện.",
    dur: 11.352,
  },
  {
    id: "s7",
    audio: "deAn06/s7.mp3",
    caption:
      "Đề án 06 — Nền tảng số cho mỗi người dân. Định danh điện tử, chia sẻ một lần, sử dụng ở mọi nơi.",
    dur: 8.256,
  },
];
