// ---------------------------------------------------------------------------
// tts.mjs — Remotion Production Contract v1 `tts` capability
// ---------------------------------------------------------------------------

import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { loadContractModule } from "./contractLoader.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// ─── TTS configuration constants ──────────────────────────────────────────
// These reflect the ACTUAL implementation in gen_tts_solarSystem.py.
// Source of truth: gen_tts_solarSystem.py line 8 (VOICE) and line 5 (edge_tts import).
export const TTS_CONFIG = {
  solarSystem: {
    ttsBackend: "edge",        // actual engine: edge_tts (Microsoft Edge TTS)
    voice: "vi-VN-NamMinhNeural", // actual voice from gen_tts_solarSystem.py line 8
    script: "gen_tts_solarSystem.py",
  },
};

// ─── Duration helpers ──────────────────────────────────────────────────────

/**
 * Read durations.json from a production's artifact root.
 * Returns total duration in seconds, or null if unavailable.
 * The durations.json is generated by the TTS script (gen_tts_solarSystem.py)
 * using mutagen.mp3 to measure actual MP3 artifact durations.
 */
function readArtifactDuration(sentinelPath) {
  try {
    if (!existsSync(sentinelPath)) return null;
    const raw = readFileSync(sentinelPath, "utf8");
    const durations = JSON.parse(raw);
    // durations.json is a map of scene IDs to individual durations
    // Sum all scene durations to get total artifact duration
    const total = Object.values(durations).reduce((sum, d) => sum + (typeof d === "number" ? d : 0), 0);
    return total > 0 ? Math.round(total * 1000) / 1000 : null;
  } catch {
    return null;
  }
}

// ─── TTS capability ───────────────────────────────────────────────────────

export async function runTts(productionId) {
  const mod = await loadContractModule("src/contract/tts.ts");
  const provMod = await loadContractModule("src/contract/provenance.ts");
  const resolution = mod.resolveTtsRequest({ productionId });
  if (resolution.status !== "SUCCESS") return resolution;

  const target = resolution.target;
  const collision = mod.ttsCollision(target, existsSync(path.join(ROOT, target.sentinel)));
  if (collision.status !== "SUCCESS") return collision;

  // Get TTS configuration for this production
  const config = TTS_CONFIG[productionId];
  if (!config) {
    return { status: "BLOCKED", message: `no TTS configuration for production "${productionId}"` };
  }

  // Implementation-specific delegation
  let genResult;
  if (productionId === "solarSystem") {
    const r = spawnSync("python", [path.join(ROOT, config.script)], { cwd: ROOT, stdio: "inherit" });
    if (r.status !== 0) return { status: "FAILED", message: "TTS generation failed" };
    genResult = { status: "SUCCESS", message: "TTS generation completed" };
  } else if (productionId === "solarSystem-contract-test") {
    const r = spawnSync("python", [path.join(ROOT, config.script), target.artifactRoot], { cwd: ROOT, stdio: "inherit" });
    if (r.status !== 0) return { status: "FAILED", message: "TTS generation failed" };
    genResult = { status: "SUCCESS", message: "TTS generation completed" };
  } else {
    return { status: "BLOCKED", message: `no generation path for production "${productionId}"` };
  }

  // Generate provenance for successful TTS
  const sentinelPath = path.join(ROOT, target.sentinel);
  let artifactSize = null;
  try {
    if (existsSync(sentinelPath)) {
      artifactSize = statSync(sentinelPath).size;
    }
  } catch { /* ignore */ }

  const contract = JSON.parse(readFileSync(path.join(ROOT, "contract.json"), "utf8"));
  const composition = contract.productions[productionId]?.composition || "unknown";

  const provenance = provMod.generateProvenance({
    productionId,
    contractVersion: contract.contractVersion,
    composition,
    ttsBackend: config.ttsBackend,
    voice: config.voice,
    duration: readArtifactDuration(target.sentinel),
    artifactPath: target.sentinel,
    artifactSize,
    repoRoot: ROOT,
  });

  // Write provenance sidecar
  const provPath = provMod.provenancePath(target.sentinel);
  writeFileSync(path.join(ROOT, provPath), JSON.stringify(provenance, null, 2));

  return { ...genResult, provenance };
}

async function main() {
  const productionId = process.argv[2];
  if (!productionId) { console.error("Usage: npm run tts -- <productionId>"); process.exit(1); }
  const out = await runTts(productionId);
  console.log(JSON.stringify(out, null, 2));
  process.exit(out.status === "SUCCESS" ? 0 : out.status === "BLOCKED" ? 2 : 1);
}

const invoked = process.argv[1] ? pathToFileURL(process.argv[1]).href : "";
if (invoked.endsWith("/scripts/tts.mjs")) main();
