// ---------------------------------------------------------------------------
// Luật Trật tự, an toàn giao thông đường bộ 2024 Content Data
//
// Luật số 36/2024/QH15 — Luật Trật tự, an toàn giao thông đường bộ
// Ký ngày 27/06/2024, có hiệu lực từ 01/01/2025
//
// All facts verified from official sources:
// - Luật số 36/2024/QH15 (Cổng Thông tin điện tử Chính phủ)
// - Nghị định 168/2024/NĐ-CP (xử phạt vi phạm hành chính giao thông)
// - Bộ Công an (mps.gov.vn)
// - Thư viện Pháp luật (thuvienphapluat.vn)
//
// No colors, no fonts, no positions, no presentation.
// Audio: Vietnamese TTS narration via Edge TTS (vi-VN-NamMinhNeural).
// Generated by gen_tts_luatGTDB.py → public/luatGTDB/s{N}.mp3
// ---------------------------------------------------------------------------

import { FPS, TAIL, sceneFrames } from "./nq57";
import type { SceneDef, NQ57SceneContent } from "./nq57";

export { FPS, TAIL, sceneFrames };

// ---------------------------------------------------------------------------
// Luật GTDB Content -- scene-specific content
// ---------------------------------------------------------------------------

export const LUAT_GTDB_CONTENT: Record<string, NQ57SceneContent> = {
  s1: {
    kind: "title",
    badge: "QUỐC HỘI · KHÓA XV · 27/06/2024",
    title: "LUẬT 36/2024/QH15",
    subtitle: "Trật tự, an toàn giao thông đường bộ — Hiệu lực 01/01/2025",
    tagline: "Luật mới, quy chuẩn mới, trách nhiệm mới",
  },

  s2: {
    kind: "quote",
    text: "Thay thế Luật Giao thông đường bộ 2008, Luật 36/2024/QH15 quy định toàn diện về trật tự, an toàn giao thông đường bộ, bao gồm tổ chức giao thông, phương tiện, người lái xe và trách nhiệm của các cơ quan quản lý.",
    keyPhrases: ["Luật 36/2024/QH15", "trật tự, an toàn giao thông đường bộ"],
  },

  s3: {
    kind: "pillars",
    title: "Nội dung chính",
    subtitle: "5 nhóm quy định mới nổi bật",
    pillars: [
      "Bằng lái xe có điểm",
      "An toàn trẻ em trên xe",
      "Xe đưa đón học sinh",
      "Biển số định danh",
      "Phân hạng giấy phép lái xe",
    ],
  },

  s4: {
    kind: "stats",
    title: "Bằng lái xe — Hệ thống 12 điểm",
    chartData: [
      { label: "Mới cấp", value: 12 },
      { label: "Vi phạm nhẹ", value: -1 },
      { label: "Vi phạm nặng", value: -2 },
      { label: "Trọng tội", value: -4 },
      { label: "Mất điểm", value: 0 },
    ],
    gauges: [
      { value: 12, max: 12, label: "Điểm GPLX khi mới cấp", unit: "điểm" },
      { value: 6, max: 12, label: "Điểm còn lại sau vi phạm", unit: "điểm" },
      { value: 50, max: 100, label: "Tiếp tục lái xe (>6 điểm)", unit: "%" },
    ],
  },

  s5: {
    kind: "roles",
    sectionTitle: "ĐIỂM MỚI QUAN TRỌNG",
    roles: [
      { title: "Trẻ em dưới 10 tuổi", subtitle: "Không được ngồi hàng ghế trước trên ô tô" },
      { title: "Xe đưa đón học sinh", subtitle: "Bắt buộc camera + thiết bị cảnh báo quên trẻ" },
      { title: "Xe máy chở 2 người", subtitle: "Được phép khi chở người già, khuyết tật, trẻ em dưới 12" },
    ],
  },

  s6: {
    kind: "vision",
    label: "XỬ PHẠT",
    targetValue: 50,
    subtitle: "Nghị định 168/2024/NĐ-CP — Mức phạt mới",
    description: "Phạt từ 400.000đ đến 50.000.000đ tùy mức độ vi phạm",
  },

  s7: {
    kind: "end",
    title: "An toàn giao thông",
    subtitle: "Luật 36/2024/QH15 — Vì sự an toàn của mỗi người",
    reference: "LUẬT 36/2024/QH15",
  },
};

// ---------------------------------------------------------------------------
// Scene definitions -- ordered scene list with audio + timing
//
// Audio: Vietnamese TTS narration (Edge TTS, vi-VN-NamMinhNeural).
// Generated by gen_tts_luatGTDB.py → public/luatGTDB/s{N}.mp3
// ---------------------------------------------------------------------------

export const LUAT_GTDB_SCENES: SceneDef[] = [
  {
    id: "s1",
    audio: "luatGTDB/s1.mp3",
    caption:
      "Chào bạn. Hôm nay chúng ta cùng tìm hiểu về Luật Trật tự, an toàn giao thông đường bộ — Luật số 36/2024/QH15, có hiệu lực từ ngày 1 tháng 1 năm 2025.",
    dur: 13.992,
  },
  {
    id: "s2",
    audio: "luatGTDB/s2.mp3",
    caption:
      "Luật 36/2024/QH15 thay thế Luật Giao thông đường bộ 2008, quy định toàn diện về trật tự, an toàn giao thông đường bộ, bao gồm tổ chức giao thông, phương tiện, người lái xe và trách nhiệm của các cơ quan quản lý.",
    dur: 14.088,
  },
  {
    id: "s3",
    audio: "luatGTDB/s3.mp3",
    caption:
      "Năm nhóm quy định mới nổi bật: Bằng lái xe có điểm, An toàn trẻ em trên xe, Xe đưa đón học sinh, Biển số định danh và Phân hạng giấy phép lái xe.",
    dur: 9.528,
  },
  {
    id: "s4",
    audio: "luatGTDB/s4.mp3",
    caption:
      "Hệ thống bằng lái xe 12 điểm: Khi mới cấp có 12 điểm, bị trừ theo mức độ vi phạm. Mất hết 12 điểm phải ngừng lái xe, sau 6 tháng mới được thi lại để khôi phục.",
    dur: 12.48,
  },
  {
    id: "s5",
    audio: "luatGTDB/s5.mp3",
    caption:
      "Điểm mới quan trọng: Trẻ em dưới 10 tuổi không được ngồi hàng ghế trước trên ô tô. Xe đưa đón học sinh phải có camera và thiết bị cảnh báo quên trẻ. Xe máy được chở 2 người trong trường hợp đặc biệt.",
    dur: 13.776,
  },
  {
    id: "s6",
    audio: "luatGTDB/s6.mp3",
    caption:
      "Nghị định 168/2024/NĐ-CP quy định mức phạt mới: từ 400.000 đồng cho vi phạm nhẹ đến 50.000.000 đồng cho các hành vi vi phạm nghiêm trọng như đua xe, sử dụng chân điều khiển vô lăng.",
    dur: 12.504,
  },
  {
    id: "s7",
    audio: "luatGTDB/s7.mp3",
    caption:
      "Luật 36/2024/QH15 — Vì sự an toàn của mỗi người. Tuân thủ pháp luật, bảo vệ tính mạng chính mình và cộng đồng.",
    dur: 9.816,
  },
];
