// ---------------------------------------------------------------------------
// Nghị Quyết 79 Content Data
//
// Nghị quyết 79-NQ/TW của Bộ Chính trị về phát triển kinh tế nhà nước
// (Ngày 06/01/2026, ký bởi Tổng Bí thư Tô Lâm)
//
// All facts verified from official source:
// - Cổng Thông tin điện tử Chính phủ: xaydungchinhsach.chinhphu.vn
// - Toàn văn Nghị quyết 79-NQ/TW
//
// No colors, no fonts, no positions, no presentation.
// Audio: generated separately via gen_tts_nghiQuyet79.py
// ---------------------------------------------------------------------------

import { FPS, TAIL, sceneFrames } from "./nq57";
import type { SceneDef, NQ57SceneContent } from "./nq57";

export { FPS, TAIL, sceneFrames };

// ---------------------------------------------------------------------------
// Nghị Quyết 79 Content -- scene-specific content
// ---------------------------------------------------------------------------

export const NGHI_QUYET_79_CONTENT: Record<string, NQ57SceneContent> = {
  s1: {
    kind: "title",
    badge: "BỘ CHÍNH TRỊ · 06/01/2026",
    title: "NGHỊ QUYẾT 79",
    subtitle: "Phát triển kinh tế nhà nước",
    tagline: "Phát huy vai trò chủ đạo, tiên phong và định hướng chiến lược",
  },

  s2: {
    kind: "quote",
    text:
      "Kinh tế nhà nước là thành phần đặc biệt quan trọng của nền kinh tế thị trường định hướng xã hội chủ nghĩa. Nền tảng bao gồm đất đai, tài nguyên, hạ tầng, ngân sách, dự trữ quốc gia, doanh nghiệp nhà nước, tổ chức tín dụng nhà nước, vốn nhà nước tại doanh nghiệp và đơn vị sự nghiệp công lập.",
    keyPhrases: ["kinh tế nhà nước", "định hướng xã hội chủ nghĩa", "đất đai, tài nguyên, hạ tầng"],
  },

  s3: {
    kind: "roles",
    sectionTitle: "QUAN ĐIỂM CHỈ ĐẠO",
    roles: [
      {
        title: "Vai trò chủ đạo",
        subtitle: "Bảo đảm ổn định vĩ mô, định hướng chiến lược, quốc phòng, an ninh",
      },
      {
        title: "Bình đẳng & cạnh tranh",
        subtitle: "Cùng phát triển lâu dài, hợp tác và cạnh tranh lành mạnh với các khu vực kinh tế khác",
      },
      {
        title: "Khơi thông nguồn lực",
        subtitle: "Quản lý, khai thác, sử dụng hiệu quả, chống thất thoát, lãng phí",
      },
      {
        title: "Tiên phong kiến tạo",
        subtitle: "Dẫn dắt công nghiệp hóa, hiện đại hóa, làm chủ công nghệ chiến lược",
      },
    ],
  },

  s4: {
    kind: "pillars",
    title: "Nguồn lực kinh tế nhà nước",
    subtitle: "Các nhóm nguồn lực được Nhà nước nắm giữ và quản lý",
    pillars: [
      "Đất đai, tài nguyên khoáng sản, nước, biển, đảo",
      "Kết cấu hạ tầng chiến lược, hạ tầng số",
      "Ngân sách nhà nước, dự trữ quốc gia, quỹ tài chính",
      "Doanh nghiệp nhà nước, tổ chức tín dụng nhà nước",
      "Vốn nhà nước tại doanh nghiệp, đơn vị sự nghiệp công lập",
    ],
  },

  s5: {
    kind: "stats",
    title: "Mục tiêu định lượng đến năm 2030",
    chartData: [
      { label: "2026", value: 18 },
      { label: "2027", value: 18 },
      { label: "2028", value: 18 },
      { label: "2029", value: 18 },
      { label: "2030", value: 18 },
    ],
    gauges: [
      {
        value: 50,
        max: 500,
        label: "DNNN trong Top 500 Đông Nam Á",
        unit: "",
      },
      {
        value: 2,
        max: 500,
        label: "DNNN trong Top 500 Thế giới",
        unit: "",
      },
      {
        value: 100,
        max: 100,
        label: "DNNN quản trị hiện đại trên nền tảng số",
        unit: "%",
      },
      {
        value: 60,
        max: 100,
        label: "Nợ công không quá GDP",
        unit: "%",
      },
      {
        value: 35,
        max: 100,
        label: "Chi đầu tư phát triển / Tổng chi NS",
        unit: "%",
      },
    ],
  },

  s6: {
    kind: "vision",
    label: "TẦM NHÌN 2045",
    targetValue: 2,
    subtitle: "Nước phát triển, thu nhập cao",
    description:
      "Dự trữ quốc gia 2% GDP · 60 DNNN Top 500 Đông Nam Á · 5 DNNN Top 500 Thế giới · 50% đơn vị sự nghiệp tự bảo đảm · Kinh tế nhà nước tự chủ, tự cường, cạnh tranh toàn diện, hội nhập sâu rộng",
  },

  s7: {
    kind: "end",
    title: "KINH TẾ NHÀ NƯỚC",
    subtitle: "Hiệu quả hơn · Tiên phong hơn · Dẫn dắt hơn",
    reference: "Nghị quyết 79-NQ/TW · 06/01/2026",
  },
};

// ---------------------------------------------------------------------------
// Scene definitions -- ordered scene list with audio + timing
//
// Audio: generated by gen_tts_nghiQuyet79.py → public/nghiQuyet79/s{N}.mp3
// ---------------------------------------------------------------------------

export const NGHI_QUYET_79_SCENES: SceneDef[] = [
  {
    id: "s1",
    audio: "nghiQuyet79/s1.mp3",
    caption:
      "Chào bạn. Hôm nay chúng ta cùng tìm hiểu về Nghị quyết 79-NQ/TW của Bộ Chính trị — Phát triển kinh tế nhà nước. Ngày ký: 6 tháng 1 năm 2026, bởi Tổng Bí thư Tô Lâm.",
    dur: 13.848,
  },
  {
    id: "s2",
    audio: "nghiQuyet79/s2.mp3",
    caption:
      "Kinh tế nhà nước là thành phần đặc biệt quan trọng của nền kinh tế thị trường định hướng xã hội chủ nghĩa. Nền tảng bao gồm đất đai, tài nguyên, hạ tầng, ngân sách, dự trữ quốc gia, doanh nghiệp nhà nước và đơn vị sự nghiệp công lập.",
    dur: 14.352,
  },
  {
    id: "s3",
    audio: "nghiQuyet79/s3.mp3",
    caption:
      "Bốn quan điểm chỉ đạo: Kinh tế nhà nước giữ vai trò chủ đạo, bình đẳng trước pháp luật với các khu vực kinh tế khác, khơi thông và sử dụng hiệu quả nguồn lực, tiên phong kiến tạo phát triển và làm chủ công nghệ chiến lược.",
    dur: 23.232,
  },
  {
    id: "s4",
    audio: "nghiQuyet79/s4.mp3",
    caption:
      "Năm nhóm nguồn lực: đất đai và tài nguyên, kết cấu hạ tầng chiến lược, ngân sách và dự trữ quốc gia, doanh nghiệp và tổ chức tín dụng nhà nước, vốn nhà nước và đơn vị sự nghiệp công lập.",
    dur: 21.504,
  },
  {
    id: "s5",
    audio: "nghiQuyet79/s5.mp3",
    caption:
      "Mục tiêu 2030: 50 doanh nghiệp nhà nước vào Top 500 Đông Nam Á, 1 đến 3 vào Top 500 thế giới, 100% quản trị hiện đại trên nền tảng số, nợ công không quá 60% GDP, chi đầu tư 35-40% tổng chi ngân sách.",
    dur: 21.84,
  },
  {
    id: "s6",
    audio: "nghiQuyet79/s6.mp3",
    caption:
      "Tầm nhìn 2045: Dự trữ quốc gia 2% GDP, 60 doanh nghiệp nhà nước Top 500 Đông Nam Á, 5 Top 500 thế giới, 50% đơn vị sự nghiệp công lập tự bảo đảm. Kinh tế nhà nước tự chủ, tự cường, cạnh tranh toàn diện, hội nhập sâu rộng.",
    dur: 20.712,
  },
  {
    id: "s7",
    audio: "nghiQuyet79/s7.mp3",
    caption:
      "Kinh tế nhà nước: Hiệu quả hơn, tiên phong hơn, dẫn dắt hơn. Góp phần xây dựng nền kinh tế tự chủ, tự lực, tự cường, phát triển nhanh và bền vững. Nghị quyết 79-NQ/TW.",
    dur: 14.376,
  },
];